version: '3.8'

services:
  # USER SERVICE
  userservice:
    build: 
      context: .
      dockerfile: UserService/Dockerfile
    ports:
      - "5202:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=ecommercedb;Username=postgres;Password=postgres
    depends_on:
      - postgres
    networks:
      - backend
  
  # PRODUCT SERVICE
  productservice:
    build: 
      context: .
      dockerfile: ProductService/Dockerfile
    ports:
      - "5176:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=ecommercedb;Username=postgres;Password=postgres
    networks:
      - backend
  
  # CART SERVICE
  cartservice:
    build: 
      context: .
      dockerfile: CartService/Dockerfile
    ports:
      - "5259:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - Redis__Host=redis
      - Redis__Port=6379
    depends_on:
      - redis
    networks:
      - backend
  
  # ORDER SERVICE
  orderservice:
    build: 
      context: .
      dockerfile: OrderService/Dockerfile
    ports:
      - "5199:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - RabbitMQ__Host=rabbitmq
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=ecommercedb;Username=postgres;Password=postgres
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - backend
  
  # PAYMENT SERVICE
  paymentservice:
    build: 
      context: .
      dockerfile: PaymentService/Dockerfile
    ports:
      - "5208:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__Port=5672
      - RabbitMQ__User=guest
      - RabbitMQ__Password=guest
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - backend
  
  # POSTGRE SQL
  postgres:
    image: postgres:14.4-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypgdbpass
      POSTGRES_DB: ecommercedb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
  
  # REDIS
  redis:
    image: redis:6
    restart: always
    ports:
      - "6379:6379"
    networks:
      - backend
  
  # RABBIT MQ
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5672:5672" # Main RabbitMQ connection
      - "15672:15672" # RabbitMQ management dashboard
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - backend
  
  # NGINX
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    depends_on:
      - userservice
      - productservice
      - cartservice
      - orderservice
      - paymentservice
    networks:
      - backend
    
# Named Volumes
volumes:
  postgres_data:

# Custom Network
networks:
  backend:
    driver: bridge