version: '3.8'

services:
  # USER SERVICE
  userservice:
    build: ./UserService
    ports:
      - "5202:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=usersdb;Username=postgres;Password=postgres
    depends_on:
      - postgres
    networks:
      - backend
  
  # PRODUCT SERVICE
  productservice:
    build: ./ProductService
    ports:
      - "5176:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - backend
  
  # CART SERVICE
  cartservice:
    build: ./CartService
    ports:
      - "5259:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Redis__Host=redis
    depends_on:
      - redis
    networks:
      - backend
  
  # ORDER SERVICE
  orderservice:
    build: ./OrderService
    ports:
      - "5199:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMQ__Host=rabbitmq
    depends_on:
      - rabbitmq
    networks:
      - backend
  
  # PAYMENT SERVICE
  paymentservice:
    build: ./PaymentService
    ports:
      - "5208:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMQ__Host=rabbitmq
    depends_on:
      - rabbitmq
    networks:
      - backend
  
  # POSTGRE SQL
  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: usersdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
  
  # REDIS
  redis:
    image: redis:6
    restart: always
    ports:
      - "6379:6379"
    networks:
      - backend
  
  # RABBIT MQ
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "5672:5672" # Main RabbitMQ connection
      - "15672:15672" # RabbitMQ management dashboard
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - backend
  
  # NGINX
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    depends_on:
      - userservice
      - productservice
      - cartservice
      - orderservice
      - paymentservice
    networks:
      - backend
    
# Named Volumes
volumes:
  postgres_data:

# Custom Network
networks:
  backend:
    driver: bridge